// src/components/recursos/feature-icons.ts
import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  ArrowUpDown,
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  Calculator,
  Calendar,
  Check,
  CheckCircle,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  CreditCard,
  Cylinder,
  Database,
  Download,
  Edit,
  FileSearch,
  FileText,
  Fuel,
  Gift,
  GitBranch,
  Globe,
  Hash,
  History,
  Inbox,
  LayoutGrid,
  ListOrdered,
  Map,
  MapPin,
  MapPinned,
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  Monitor,
  Navigation,
  Package,
  Percent,
  Phone,
  Sliders,
  Smartphone,
  Sparkles,
  Star,
  Tag,
  Truck,
  UserCheck,
  Users,
  Wallet,
  Workflow,
  Wrench,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  'arrow-up-down': ArrowUpDown,
  'bar-chart-3': BarChart3,
  bell: Bell,
  'book-open': BookOpen,
  'building-2': Building2,
  calculator: Calculator,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle,
  'check-square': CheckSquare,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'credit-card': CreditCard,
  cylinder: Cylinder,
  database: Database,
  download: Download,
  edit: Edit,
  'file-search': FileSearch,
  'file-text': FileText,
  fuel: Fuel,
  gift: Gift,
  'git-branch': GitBranch,
  globe: Globe,
  hash: Hash,
  history: History,
  inbox: Inbox,
  'layout-grid': LayoutGrid,
  'list-ordered': ListOrdered,
  map: Map,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'message-square-text': MessageSquareText,
  monitor: Monitor,
  navigation: Navigation,
  package: Package,
  percent: Percent,
  phone: Phone,
  sliders: Sliders,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  tag: Tag,
  truck: Truck,
  'user-check': UserCheck,
  users: Users,
  wallet: Wallet,
  workflow: Workflow,
  wrench: Wrench,
};

export function getIcon(name?: string): LucideIcon {
  if (!name) return Check;
  return ICONS[name] ?? Check;
}
